const data = [
  {
    key: "selectData",
    label: "基础指标",
    list: [
      { label: "有消耗账户数", key: "burnAccountCount" },
      {
        sortable: true,
        minWidth: 130,
        key: "validImpNum",
        label: "曝光数",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 130,
        key: "totalClickNum",
        label: "点击数",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 130,
        key: "convertNum",
        label: "转化数",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 130,
        key: "ctr",
        label: "CTR",
        filter: "changePercentString",
        filterProps: ["%"],
      },
      {
        sortable: true,
        minWidth: 130,
        key: "cvr",
        label: "CVR",
        filter: "changePercentString",
        filterProps: ["%"],
      },
      {
        sortable: true,
        minWidth: 130,
        key: "validTotalBurn",
        label: "消耗",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 130,
        key: "cpm",
        label: "CPM",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 130,
        key: "cpc",
        label: "CPC",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 130,
        key: "cpa",
        label: "CPA",
        filter: "moneyFormat",
      },
    ],
  },
  {
    key: "eventData",
    label: "事件指标",
    list: [
      {
        sortable: true,
        minWidth: 130,
        key: "invokeNum",
        label: "调起数量",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 130,
        key: "invokeSuccRatio",
        label: "调起率",
        filter: "changePercentString",
        filterProps: ["%"],
      },
      {
        sortable: true,
        minWidth: 130,
        key: "invokeSuccCost",
        label: "调起成本",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 130,
        key: "firstInvokeNum",
        label: "首次调起数",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 130,
        key: "firstRatio",
        label: "首调率",
        filter: "changePercentString",
        filterProps: ["%"],
      },
      {
        sortable: true,
        minWidth: 130,
        key: "firstCost",
        label: "首调成本",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 130,
        key: "nextDayRetentionNum",
        label: "次留用户数",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 130,
        key: "nextDayRetentionSuccRatio",
        label: "次日留存率",
        filter: "changePercentString",
        filterProps: ["%"],
      },
      {
        sortable: true,
        minWidth: 140,
        key: "nextDayRetentionSuccCost",
        label: "次日留存成本",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 130,
        key: "keyPageViewNum",
        label: "关键页浏览",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 140,
        key: "keyPageViewSuccRatio",
        label: "关键页浏览率",
        filter: "changePercentString",
        filterProps: ["%"],
      },
      {
        sortable: true,
        minWidth: 150,
        key: "keyPageViewSuccCost",
        label: "关键页浏览成本",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 140,
        key: "mpInvokeNum",
        label: "小程序调起数",
        filter: "moneyFormat",
      },
      {
        sortable: true,
        minWidth: 140,
        key: "mpInvokeSuccRatio",
        label: "小程序调起率",
        filter: "changePercentString",
        filterProps: ["%"],
      },
      {
        sortable: true,
        minWidth: 150,
        key: "mpInvokeSuccCost",
        label: "小程序调起成本",
        filter: "moneyFormat",
      },
    ],
  },
];
const targetsList = data.map(item => item.list).flat().map(item => item.key)
console.log(targetsList)
